-- @ AYUSH ACHARYA TE 1
--CREATE TABLE O_ROLL_CALL(Roll_No NUMBER(5) PRIMARY KEY,Name VARCHAR2(20));
--CREATE TABLE N_ROLL_CALL(Roll_No NUMBER(5) PRIMARY KEY,Name VARCHAR2(20));
--INSERT INTO O_ROLL_CALL VALUES(01,'AYUSH ACHARYA');
--INSERT INTO O_ROLL_CALL VALUES(02,'VISHAL LATE');
--INSERT INTO O_ROLL_CALL VALUES(03,'ASHISH SHISAL');
--INSERT INTO O_ROLL_CALL VALUES(04,'SAMPADA AGHAV');
--INSERT INTO O_ROLL_CALL VALUES(05,'DIKSHA DHUMAL');
--INSERT INTO N_ROLL_CALL VALUES(10,'RAJ JAIN');
--INSERT INTO N_ROLL_CALL VALUES(11,'AKSHAY KELKAR');
SELECT * FROM O_ROLL_CALL;

SELECT * FROM N_ROLL_CALL;

DECLARE 
	Roll NUMBER(5);
	CH NUMBER(1):=0;
	CURSOR cur(roll NUMBER) IS SELECT * FROM O_ROLL_CALL WHERE Roll_no NOT IN (SELECT Roll_no FROM N_ROLL_CALL WHERE N_ROLL_CALL.Roll_No=O_ROLL_CALL.Roll_No);
	new_var N_ROLL_CALL%ROWTYPE;
	
BEGIN
	Roll:=&Roll;
	OPEN cur(Roll);
	
	LOOP FETCH cur INTO new_var;
	EXIT WHEN cur%NOTFOUND;
	
	IF (new_var.Roll_No=Roll) THEN
		INSERT INTO N_ROLL_CALL VALUES(new_var.Roll_No,new_var.Name);
		CH:=1;
	END IF;
	
	END LOOP;
	
	IF (cur%ROWCOUNT=0 OR CH=0) THEN
		DBMS_OUTPUT.PUT_LINE('RECORD PRE-EXISTS IN THE TABLE');
	ELSE
		DBMS_OUTPUT.PUT_LINE('RECORD UPDATED IN THE TABLE');
	END IF;
	
	CLOSE cur;
	
END;
/
SELECT * FROM N_ROLL_CALL;
	--just put serveroutput on  --before execution in sql*plus terminal
